/**
 * Session Live Store
 *
 * In-memory store tracking every active agent session's real-time metrics.
 * Keyed by server-generated session_id (from handoff.tools.ts generateSessionId).
 * A secondary index maps prep session_ids → server session_ids so that
 * withLogging (which only sees _session_id = prep session_id) can update the
 * correct entry.
 *
 * Exported via GET /sessions/live in http-transport.ts and read by the
 * VS Code extension's 30-second sync timer.
 */

export interface LiveSessionEntry {
  /** Server-generated session ID (canonical key) */
  serverSessionId: string;
  /** Prep session ID emitted by memory_session(action:prep) — may be undefined for legacy calls */
  prepSessionId?: string;
  /** Last tool name seen in withLogging for this session */
  lastTool: string;
  /** ISO timestamp of the last tool call */
  lastCallAt: string;
  /** Total tool calls seen for this session */
  callCount: number;
  /** Agent type from init params */
  agentType?: string;
  /** Plan ID from init params */
  planId?: string;
  /** Workspace ID from init params */
  workspaceId?: string;
  /** ISO timestamp when this session was registered */
  registeredAt: string;
}

// Primary store: serverSessionId → entry
const liveStore = new Map<string, LiveSessionEntry>();

// Secondary index: prepSessionId → serverSessionId (for withLogging lookups)
const prepToServer = new Map<string, string>();

// ---------------------------------------------------------------------------
// Mutation helpers
// ---------------------------------------------------------------------------

/**
 * Register a new live session.  Called from memory_agent case 'init'.
 *
 * @param serverSessionId  The session_id generated by store.generateSessionId()
 * @param prepSessionId    The _session_id from the tool params (may be undefined)
 * @param meta             Agent type, plan ID, workspace ID for display in dashboard
 */
export function registerLiveSession(
  serverSessionId: string,
  prepSessionId: string | undefined,
  meta: {
    agentType?: string;
    planId?: string;
    workspaceId?: string;
  }
): void {
  const now = new Date().toISOString();
  const entry: LiveSessionEntry = {
    serverSessionId,
    prepSessionId,
    lastTool: 'init',
    lastCallAt: now,
    callCount: 1,
    agentType: meta.agentType,
    planId: meta.planId,
    workspaceId: meta.workspaceId,
    registeredAt: now,
  };
  liveStore.set(serverSessionId, entry);

  if (prepSessionId) {
    prepToServer.set(prepSessionId, serverSessionId);
  }
}

/**
 * Update the last-tool and call-count for a session.
 * Accepts either a server session ID or a prep session ID — tries both.
 * Called from withLogging on every tool invocation.
 *
 * @param anyId     The _session_id from tool params (prep ID) or a raw server ID
 * @param toolName  The name of the tool that was called
 */
export function touchLiveSession(anyId: string, toolName: string): void {
  // Resolve to server session ID
  const serverSessionId = liveStore.has(anyId)
    ? anyId
    : prepToServer.get(anyId);

  if (!serverSessionId) return; // Unknown session — ignore silently

  const entry = liveStore.get(serverSessionId);
  if (!entry) return;

  entry.lastTool = toolName;
  entry.lastCallAt = new Date().toISOString();
  entry.callCount += 1;
}

/**
 * Retrieve a live session entry by either prep session ID or server session ID.
 * Returns undefined if not found.
 *
 * @param anyId  The _session_id from tool params (prep ID) or a server session ID
 */
export function getLiveSessionEntry(anyId: string): LiveSessionEntry | undefined {
  const serverSessionId = liveStore.has(anyId) ? anyId : prepToServer.get(anyId);
  if (!serverSessionId) return undefined;
  return liveStore.get(serverSessionId);
}

/**
 * Remove a session from the live store.
 * Called from memory_agent case 'complete'.
 *
 * @param serverSessionId  The canonical server session ID to remove
 */
export function clearLiveSession(serverSessionId: string): void {
  const entry = liveStore.get(serverSessionId);
  if (entry?.prepSessionId) {
    prepToServer.delete(entry.prepSessionId);
  }
  liveStore.delete(serverSessionId);
}

/**
 * Look up the server session ID for a given prep session ID.
 * Returns undefined if not found.
 */
export function serverSessionIdForPrepId(prepSessionId: string): string | undefined {
  return prepToServer.get(prepSessionId);
}

// ---------------------------------------------------------------------------
// Read helpers
// ---------------------------------------------------------------------------

/**
 * Return all live sessions as a plain object for HTTP serialisation.
 * Keyed by server session ID.
 */
export function getAllLiveSessions(): Record<string, LiveSessionEntry> {
  return Object.fromEntries(liveStore.entries());
}

/**
 * Return the total number of currently tracked live sessions.
 */
export function getLiveSessionCount(): number {
  return liveStore.size;
}
