#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Start the Project Memory MCP Supervisor.

.DESCRIPTION
    Ensures a supervisor.toml config exists at %APPDATA%\ProjectMemory\supervisor.toml,
    writes a default one if missing, then launches supervisor.exe from the release build.

.PARAMETER DebugMode
    Pass --debug to supervisor for verbose output.

.PARAMETER Config
    Override the config file path (default: %APPDATA%\ProjectMemory\supervisor.toml).

.PARAMETER SkipConfigInit
    Do not write a default config if one is missing — fail instead.

.EXAMPLE
    .\start-supervisor.ps1

.EXAMPLE
    .\start-supervisor.ps1 -DebugMode

.EXAMPLE
    .\start-supervisor.ps1 -Config "C:\MyConfig\supervisor.toml"
#>

[CmdletBinding()]
param(
    [switch]$DebugMode,
    [string]$Config = '',
    [switch]$SkipConfigInit
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Root = $PSScriptRoot
$ExePath = Join-Path $Root 'target\release\supervisor.exe'

if (-not (Test-Path $ExePath)) {
    Write-Host '✗ supervisor.exe not found. Run .\install.ps1 -Component Supervisor first.' -ForegroundColor Red
    exit 1
}

# ── Config bootstrap ──────────────────────────────────────────────────────────

$ConfigPath = if ($Config) {
    $Config
} else {
    Join-Path $env:APPDATA 'ProjectMemory\supervisor.toml'
}

if (-not (Test-Path $ConfigPath)) {
    if ($SkipConfigInit) {
        Write-Host "✗ Config not found at $ConfigPath and -SkipConfigInit was set." -ForegroundColor Red
        exit 1
    }

    Write-Host "No config found at $ConfigPath — writing default config..." -ForegroundColor Yellow
    $ConfigDir = Split-Path $ConfigPath
    if (-not (Test-Path $ConfigDir)) {
        New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
    }

    $InteractiveTermExe = Join-Path $Root 'interactive-terminal\target\release\interactive-terminal.exe'
    $BrainstormGuiExe   = Join-Path $Root 'target\release\pm-brainstorm-gui.exe'
    $ApprovalGuiExe     = Join-Path $Root 'target\release\pm-approval-gui.exe'
    $ServerDir          = Join-Path $Root 'server'
    $DashboardServerDir = Join-Path $Root 'dashboard\server'

    $toml = @"
# Project Memory MCP — Supervisor Configuration
# Auto-generated by start-supervisor.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Full reference: supervisor/supervisor.example.toml

[supervisor]
log_level          = "info"
control_transport  = "named_pipe"
control_pipe       = "\\\\.\\pipe\\project-memory-supervisor"

[mcp]
enabled            = true
port               = 3457
backend            = "node"

[mcp.node]
command            = "node"
args               = ["dist/server.js"]
working_dir        = '$($ServerDir)'

[interactive_terminal]
enabled            = true
port               = 3458
command            = '$($InteractiveTermExe)'

[brainstorm_gui]
enabled            = true
command            = '$($BrainstormGuiExe)'
timeout_seconds    = 300
window_width       = 720
window_height      = 640

[approval_gui]
enabled            = true
command            = '$($ApprovalGuiExe)'
timeout_seconds    = 60
window_width       = 480
window_height      = 320
always_on_top      = true

[dashboard]
enabled            = true
port               = 3001
command            = "node"
args               = ["dist/index.js"]
working_dir        = '$($DashboardServerDir)'

[approval]
default_countdown_seconds = 60
default_on_timeout        = "approve"
always_on_top             = true
"@

    Set-Content -Path $ConfigPath -Value $toml -Encoding UTF8
    Write-Host "✓ Default config written to $ConfigPath" -ForegroundColor Green
    Write-Host "  Edit it to customise paths, ports, and behaviour." -ForegroundColor DarkGray
}

# ── Existing instance check (no script-owned tree cleanup) ───────────────────

$existing = @(Get-Process -Name 'supervisor' -ErrorAction SilentlyContinue |
    Where-Object { $_.Path -eq $ExePath })

if ($existing.Count -gt 0) {
    Write-Host "✗ Supervisor is already running (PID(s): $($existing.Id -join ', '))." -ForegroundColor Red
    Write-Host "  Use .\stop-supervisor.ps1 to request app shutdown first." -ForegroundColor DarkGray
    exit 1
}

# ── Launch ────────────────────────────────────────────────────────────────────

$supervisorArgs = [System.Collections.ArrayList]@()
if ($Config)    { [void]$supervisorArgs.AddRange([string[]]@('--config', $ConfigPath)) }
if ($DebugMode) { [void]$supervisorArgs.Add('--debug') }

$LogDir = Join-Path $env:APPDATA 'ProjectMemory\logs'
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Force -Path $LogDir | Out-Null }

Write-Host ''
Write-Host 'Starting supervisor...' -ForegroundColor Cyan
Write-Host "  Exe:    $ExePath" -ForegroundColor DarkGray
Write-Host "  Config: $ConfigPath" -ForegroundColor DarkGray
Write-Host "  Logs:   $LogDir" -ForegroundColor DarkGray
if ($supervisorArgs.Count -gt 0) {
    Write-Host "  Args:   $($supervisorArgs -join ' ')" -ForegroundColor DarkGray
}
Write-Host ''
Write-Host 'Supervisor is running in this window. Press Ctrl+C to stop.' -ForegroundColor Yellow
Write-Host ''

$exitCode = 0
& $ExePath @supervisorArgs
$exitCode = $LASTEXITCODE

Write-Host ''
if ($exitCode -ne 0) {
    Write-Host "Supervisor exited with code $exitCode." -ForegroundColor Red
    Write-Host "Logs: $LogDir" -ForegroundColor DarkGray
} else {
    Write-Host 'Supervisor stopped cleanly.' -ForegroundColor Green
}
