# =============================================================================
# Project Memory — Podman Compose
#
# Usage:
#   podman-compose up --build       (build & start)
#   podman-compose up -d            (start detached)
#   podman-compose down             (stop & remove)
#   podman-compose logs -f          (follow logs)
#
# @see Phase 6B.5 of docs/infrastructure-improvement-plan.md
# =============================================================================

version: "3.8"

services:
  project-memory:
    build:
      context: .
      dockerfile: Containerfile
    container_name: project-memory
    ports:
      - "3000:3000"   # MCP server (Streamable HTTP + SSE)
      - "3001:3001"   # Dashboard Express API
      - "3002:3002"   # Dashboard WebSocket
    volumes:
      - ./data:/data                # Persistent workspace data
      - ./agents:/agents:ro         # Agent files (read-only)
      # Additional workspace mounts are added dynamically by run-container.ps1
      # which reads workspace-registry.json and mounts each registered directory
    environment:
      - MBS_DATA_ROOT=/data
      - MBS_AGENTS_ROOT=/agents
      - MBS_HOST_MCP_URL=${MBS_HOST_MCP_URL}
      - MBS_WORKSPACE_MOUNTS=${MBS_WORKSPACE_MOUNTS:-{}}
      - PM_RUNNING_IN_CONTAINER=true
      - PM_TERM_ADAPTER_MODE=${PM_TERM_ADAPTER_MODE:-container_bridge}
      - PM_INTERACTIVE_TERMINAL_HOST_ALIAS=${PM_INTERACTIVE_TERMINAL_HOST_ALIAS:-host.containers.internal}
      - PM_INTERACTIVE_TERMINAL_HOST_FALLBACK_ALIAS=${PM_INTERACTIVE_TERMINAL_HOST_FALLBACK_ALIAS:-host.docker.internal}
      - PM_INTERACTIVE_TERMINAL_HOST_PORT=${PM_INTERACTIVE_TERMINAL_HOST_PORT:-45459}
      - PM_INTERACTIVE_TERMINAL_CONNECT_TIMEOUT_MS=${PM_INTERACTIVE_TERMINAL_CONNECT_TIMEOUT_MS:-3000}
      - PM_INTERACTIVE_TERMINAL_REQUEST_TIMEOUT_MS=${PM_INTERACTIVE_TERMINAL_REQUEST_TIMEOUT_MS:-30000}
      - PM_INTERACTIVE_TERMINAL_TRACE_BRIDGE=${PM_INTERACTIVE_TERMINAL_TRACE_BRIDGE:-0}
      - MCP_PORT=3000
      - DASHBOARD_PORT=3001
      - WS_PORT=3002
      - NODE_ENV=production
    extra_hosts:
      # NOTE: host-gateway resolves to the Podman bridge gateway (10.88.0.1)
      # on WSL2, NOT the Windows host. For reliable container-to-host
      # connectivity, use run-container.ps1 which auto-detects the physical
      # NIC IP. If using podman-compose directly, set the env var:
      #   PM_INTERACTIVE_TERMINAL_HOST_IP=<your-host-ip>
      # and change this to:
      #   "host.containers.internal:${PM_INTERACTIVE_TERMINAL_HOST_IP}"
      - "host.containers.internal:host-gateway"
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "node", "-e", "const http=require('http');const r=http.get('http://localhost:3000/health',res=>{process.exit(res.statusCode===200?0:1)});r.on('error',()=>process.exit(1));r.setTimeout(3000,()=>{r.destroy();process.exit(1)})"]
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 3
