/**
 * Handoff Stats & Incident Report Type Definitions
 *
 * Types for session-level instrumentation metrics, incident reports,
 * difficulty profiles, and stats validation.
 */

// =============================================================================
// Handoff Stats — Per-session instrumentation metrics
// =============================================================================

/**
 * Metrics auto-collected by the MCP server during an agent session.
 * Agents may also self-report these for cross-validation.
 */
export interface HandoffStats {
  /** Number of plan steps marked 'done' during this session */
  steps_completed: number;
  /** Number of plan steps marked 'active' (attempted) during this session */
  steps_attempted: number;
  /** Number of file read operations performed */
  files_read: number;
  /** Number of file write/modify operations performed */
  files_modified: number;
  /** Total number of MCP tool calls made */
  tool_call_count: number;
  /** Number of tool calls that failed and were retried */
  tool_retries: number;
  /** Number of steps that hit 'blocked' status */
  blockers_hit: number;
  /** Number of scope escalation events */
  scope_escalations: number;
  /** Number of context reads not in the initial context bundle */
  unsolicited_context_reads: number;
  /** Session duration classification based on wall-clock time */
  duration_category: 'quick' | 'moderate' | 'extended';
}

// =============================================================================
// Stats Validation — Cross-check agent-reported vs MCP-tracked stats
// =============================================================================

/** Describes a single metric discrepancy between agent and MCP counts */
export interface StatsDiscrepancy {
  /** The metric name that differs */
  metric: string;
  /** The value expected (from MCP tracking) */
  expected: number;
  /** The value reported by the agent */
  actual: number;
}

/**
 * Result of comparing agent-reported stats against MCP-tracked stats.
 * Used during handoff to verify agent accuracy.
 */
export interface StatsValidationResult {
  /** Whether all metrics match between agent and MCP */
  matches: boolean;
  /** List of metrics where values differ */
  discrepancies: StatsDiscrepancy[];
  /** Stats as tracked by the MCP server */
  mcp_tracked: HandoffStats;
  /** Stats as reported by the agent */
  agent_reported: HandoffStats;
}

// =============================================================================
// Incident Report — Generated by Revisionist on every invocation
// =============================================================================

/**
 * Structured report generated when an agent session encounters blockers
 * or when a Revisionist agent is invoked. Captures what went wrong and
 * recommended fixes.
 */
export interface IncidentReport {
  /** Plan this incident relates to */
  plan_id: string;
  /** Session where the incident occurred */
  session_id: string;
  /** Agent type that triggered or experienced the incident */
  agent_type: string;
  /** ISO timestamp of when the incident was recorded */
  timestamp: string;
  /** What triggered the incident (e.g. build failure, blocked step) */
  trigger_reason: string;
  /** Analysis of the underlying cause */
  root_cause_analysis: string;
  /** Step descriptions that were blocked */
  blocked_steps: string[];
  /** Actions taken or recommended to resolve the incident */
  resolution_actions: string[];
  /** Session metrics snapshot at the time of the incident */
  stats_snapshot: HandoffStats;
  /** Suggestions for preventing similar incidents */
  recommendations: string[];
}

// =============================================================================
// Difficulty Profile — Aggregated stats across a plan's lifecycle
// =============================================================================

/**
 * Aggregated view of a plan's complexity, built by the Archivist
 * when archiving a plan. Used for skill-creation decisions and
 * future estimation.
 */
export interface DifficultyProfile {
  /** Plan this profile describes */
  plan_id: string;
  /** Total number of agent sessions across the plan */
  total_sessions: number;
  /** Sum of all session stats across the plan */
  aggregated_stats: HandoffStats;
  /** Computed complexity score (higher = harder) */
  complexity_score: number;
  /** Most frequently encountered blockers across sessions */
  common_blockers: string[];
  /** Skill areas where agents struggled or needed extra sessions */
  skill_gaps_identified: string[];
  /** ISO timestamp of when this profile was created */
  created_at: string;
}
