/// PairingDialog — QR code pairing overlay.
/// Ported from supervisor/qml/PairingDialog.qml.
/// QR generation uses the `qrcode` crate (pure Rust; no CxxQt QrPairingBridge).

use iced::{
    widget::{button, column, container, row, text, Space, svg, checkbox, pick_list, scrollable, text_input},
    Alignment, Background, Border, Color, Element, Length,
};

use crate::app_state::AppState;
use crate::Message;
use super::theme;

pub fn view<'a>(
    state: &'a AppState,
    on_close:   Message,
    on_refresh: Message,
) -> Element<'a, Message>
{
    // QR SVG — generated by app logic and stored in AppState
    let qr_content: Element<'a, Message> = if state.pairing_qr_svg.is_empty() {
        container(
            text("Generating QR…")
                .size(11)
                .color(theme::TEXT_SECONDARY),
        )
        .width(Length::Fixed(200.0))
        .height(Length::Fixed(200.0))
        .style(|_| iced::widget::container::Style {
            background: Some(Background::Color(Color::from_rgb8(0x0d, 0x11, 0x17))),
            border: Border {
                color: theme::BORDER_SUBTLE,
                width: 1.0,
                ..Default::default()
            },
            ..Default::default()
        })
        .into()
    } else {
        svg::Svg::new(svg::Handle::from_memory(state.pairing_qr_svg.as_bytes().to_vec()))
            .width(Length::Fixed(200.0))
            .height(Length::Fixed(200.0))
            .into()
    };

    // ── App Selection ────────────────────────────────────────────────────────
    let apps = ["terminal", "files", "dashboard", "supervisor"];
    let mut app_checks = column![
        text("Allowed Apps")
            .size(12)
            .color(theme::TEXT_PRIMARY)
            .width(Length::Fill),
    ].spacing(4);

    for app in apps {
        let is_checked = state.pairing_allowed_apps.contains(&app.to_string());
        app_checks = app_checks.push(
            checkbox(app, is_checked)
                .on_toggle(move |_| Message::PairingToggleApp(app.to_string()))
                .size(16)
                .text_size(11)
        );
    }

    // ── Monitor Selection ────────────────────────────────────────────────────
    let monitor_picker = column![
        text("Remote Monitor")
            .size(12)
            .color(theme::TEXT_PRIMARY)
            .width(Length::Fill),
        pick_list(
            &state.available_monitors,
            state.available_monitors.get(state.pairing_selected_monitor as usize),
            |m| {
                let idx = state.available_monitors.iter().position(|x| x == m).unwrap_or(0);
                Message::PairingMonitorSelected(idx as i32)
            }
        )
        .placeholder("Select monitor…")
        .text_size(11)
        .width(Length::Fill),
    ].spacing(4);

    let auth_controls = column![
        text("Manual Pairing")
            .size(12)
            .color(theme::TEXT_PRIMARY)
            .width(Length::Fill),
        text(format!("PIN: {}", state.pairing_pin))
            .size(16)
            .color(Color::from_rgb8(0x58, 0xa6, 0xff)),
        text_input("Set session password…", &state.pairing_password)
            .on_input(|p| Message::PairingPasswordChanged(p))
            .size(11)
            .padding(8),
    ].spacing(8);

    let api_key_label = text(format!("Key: {}", state.pairing_api_key))
        .size(9)
        .color(theme::TEXT_SECONDARY)
        .width(Length::Fill);

    let buttons = row![
        button(text("Refresh").size(11)).on_press(on_refresh),
        Space::new(Length::Fill, 0.0),
        button(text("Close").size(11)).on_press(on_close),
    ]
    .spacing(8)
    .align_y(Alignment::Center)
    .width(Length::Fill);

    let dialog_body = column![
        text("Pair Mobile Device")
            .size(15)
            .color(theme::TEXT_PRIMARY)
            .width(Length::Fill),
        row![
            container(qr_content).align_x(Alignment::Center).width(Length::Fixed(200.0)),
            Space::new(Length::Fixed(16.0), 0.0),
            column![
                app_checks,
                Space::new(0.0, 12.0),
                monitor_picker,
                Space::new(0.0, 12.0),
                auth_controls,
            ].width(Length::Fill)
        ].width(Length::Fill),
        api_key_label,
        buttons,
    ]
    .spacing(12)
    .padding(20)
    .width(Length::Fixed(480.0));

    // Dimmed backdrop + centered dialog
    container(
        container(dialog_body)
            .style(|_| iced::widget::container::Style {
                background: Some(Background::Color(Color::from_rgb8(0x1c, 0x21, 0x28))),
                border: Border {
                    color: theme::BORDER_SUBTLE,
                    width: 1.0,
                    radius: 8.0.into(),
                },
                ..Default::default()
            }),
    )
    .width(Length::Fill)
    .height(Length::Fill)
    .align_x(Alignment::Center)
    .align_y(Alignment::Center)
    .style(|_| iced::widget::container::Style {
        background: Some(Background::Color(Color { r: 0.0, g: 0.0, b: 0.0, a: 0.7 })),
        ..Default::default()
    })
    .into()
}

// ── QR generation helper ──────────────────────────────────────────────────────
/// Generate an SVG QR code string for the given data.
pub fn generate_qr_svg(data: &str) -> Option<String> {
    use qrcode::{QrCode, EcLevel};
    use qrcode::render::svg;

    let code = QrCode::with_error_correction_level(data, EcLevel::M).ok()?;
    let svg_string = code.render::<svg::Color>()
        .min_dimensions(200, 200)
        .build();
    Some(svg_string)
}
