/// PairingDialog — QR code pairing overlay.
/// Ported from supervisor/qml/PairingDialog.qml.
/// QR generation uses the `qrcode` crate (pure Rust; no CxxQt QrPairingBridge).

use iced::{
    widget::{button, column, container, row, text, Space, svg},
    Alignment, Background, Border, Color, Element, Length, Padding,
};

use crate::app_state::AppState;
use super::theme;

pub fn view<'a, Message>(
    state: &'a AppState,
    on_close:   Message,
    on_refresh: Message,
) -> Element<'a, Message>
where
    Message: Clone + 'a,
{
    // QR SVG — generated by app logic and stored in AppState
    let qr_content: Element<'a, Message> = if state.pairing_qr_svg.is_empty() {
        container(
            text("Generating QR…")
                .size(11)
                .color(theme::TEXT_SECONDARY),
        )
        .width(Length::Fixed(220.0))
        .height(Length::Fixed(220.0))
        .style(|_| iced::widget::container::Style {
            background: Some(Background::Color(Color::from_rgb8(0x0d, 0x11, 0x17))),
            border: Border {
                color: theme::BORDER_SUBTLE,
                width: 1.0,
                ..Default::default()
            },
            ..Default::default()
        })
        .into()
    } else {
        svg::Svg::new(svg::Handle::from_memory(state.pairing_qr_svg.as_bytes().to_vec()))
            .width(Length::Fixed(220.0))
            .height(Length::Fixed(220.0))
            .into()
    };

    let api_key_label = text(format!("API Key: {}", state.pairing_api_key))
        .size(10)
        .color(theme::TEXT_SECONDARY)
        .width(Length::Fill);

    let buttons = row![
        button(text("Refresh Key").size(12)).on_press(on_refresh),
        Space::new(Length::Fill, 0.0),
        button(text("Close").size(12)).on_press(on_close),
    ]
    .spacing(8)
    .align_y(Alignment::Center)
    .width(Length::Fill);

    let dialog_body = column![
        text("Scan this QR code with the Project Memory mobile app")
            .size(13)
            .color(theme::TEXT_PRIMARY)
            .width(Length::Fill),
        container(qr_content).align_x(Alignment::Center).width(Length::Fill),
        api_key_label,
        buttons,
    ]
    .spacing(12)
    .padding(16)
    .width(Length::Fixed(360.0));

    // Dimmed backdrop + centered dialog
    container(
        container(dialog_body)
            .style(|_| iced::widget::container::Style {
                background: Some(Background::Color(Color::from_rgb8(0x1c, 0x21, 0x28))),
                border: Border {
                    color: theme::BORDER_SUBTLE,
                    width: 1.0,
                    radius: 6.0.into(),
                },
                ..Default::default()
            }),
    )
    .width(Length::Fill)
    .height(Length::Fill)
    .align_x(Alignment::Center)
    .align_y(Alignment::Center)
    .style(|_| iced::widget::container::Style {
        background: Some(Background::Color(Color { r: 0.0, g: 0.0, b: 0.0, a: 0.6 })),
        ..Default::default()
    })
    .into()
}

// ── QR generation helper ──────────────────────────────────────────────────────
/// Generate an SVG QR code string for the given data.
pub fn generate_qr_svg(data: &str) -> Option<String> {
    use qrcode::{QrCode, EcLevel};
    use qrcode::render::svg;

    let code = QrCode::with_error_correction_level(data, EcLevel::M).ok()?;
    let svg_string = code.render::<svg::Color>()
        .min_dimensions(200, 200)
        .build();
    Some(svg_string)
}
