export const SPAWN_REASON_CODES = {
    SPAWN_ACCEPTED: 'SPAWN_ACCEPTED',
    SPAWN_REJECT_ACTIVE_LANE: 'SPAWN_REJECT_ACTIVE_LANE',
    SPAWN_REJECT_DUPLICATE_DEBOUNCE: 'SPAWN_REJECT_DUPLICATE_DEBOUNCE',
    SPAWN_QUEUED_OPTIONAL: 'SPAWN_QUEUED_OPTIONAL',
    SPAWN_CANCELLED_TOKEN: 'SPAWN_CANCELLED_TOKEN',
    SPAWN_RELEASE_COMPLETE: 'SPAWN_RELEASE_COMPLETE',
    SPAWN_RELEASE_HANDOFF: 'SPAWN_RELEASE_HANDOFF',
    SPAWN_RELEASE_ERROR_PATH: 'SPAWN_RELEASE_ERROR_PATH',
    SPAWN_STALE_RECOVERY: 'SPAWN_STALE_RECOVERY',
    SPAWN_PREP_ONLY: 'SPAWN_PREP_ONLY',
    SPAWN_PREP_LEGACY_ALIAS: 'SPAWN_PREP_LEGACY_ALIAS',
    SPAWN_PREP_DEPRECATED_INPUT_IGNORED: 'SPAWN_PREP_DEPRECATED_INPUT_IGNORED',
    SPAWN_PREP_CONTEXT_PARTIAL: 'SPAWN_PREP_CONTEXT_PARTIAL'
} as const;

export type SpawnReasonCode = typeof SPAWN_REASON_CODES[keyof typeof SPAWN_REASON_CODES];

export interface SpawnRequestFingerprint {
    workspace_id: string;
    plan_id: string;
    agent_name: string;
    normalized_prompt: string;
    scope_key: string;
    fingerprint: string;
}
